#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run dev &
SERVER_PID=$!
npx wait-on http://localhost:5173
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo 'Vite server did not start. Push aborted.'
  kill $SERVER_PID
  exit 1
fi
npm test
TEST_RESULT=$?
kill $SERVER_PID
if [ $TEST_RESULT -ne 0 ]; then
  echo 'Tests failed. Push aborted.'
  exit 1
fi
